apiVersion: v2
name: kyverno-policies-ux
appVersion: master
description: Giant Swarm policies supporting user experience.
home: https://github.com/giantswarm/kyverno-policies-ux
icon: https://s.giantswarm.io/app-icons/kyverno/1/light.svg
annotations:
  io.giantswarm.application.team: honeybadger
version: 0.13.1-dev
