managementCluster:
  name: ""

provider:
  kind: ""
  flavor: ""

preventDeletionLabelPolicy:
  resources:
    - App
    - AWSCluster
    - AWSControlPlane
    - AWSMachineDeployment
    - AzureCluster
    - AzureMachinePool
    - cluster.x-k8s.io/v1beta2/Cluster
    - ConfigMap
    - G8sControlPlane
    - KubeadmControlPlane
    - MachineDeployment
    - MachinePool
    - Namespace
    - Organization
    - Secret
    - VCDCluster
    - VSphereCluster
  # Needed for resources that have duplicated names across different apiGroups, eg: cluster.postgresql.org/v1/Cluster and cluster.x-k8s.io/v1beta2/Cluster
  gvk:
    - cluster.x-k8s.io/v1beta2/Cluster
